### PR TITLE
Auth Features

### PR DESCRIPTION
**Pull request by isik5**
login feature and login url added

### CODE REVIEW

**Comment by isik5** [comment]
I didn't want to merge my pull requests but couldn't able to get rid of them :/ And also PyCharm has crashed several times during my push to dev that's why there is 3 login feature and login url added commits. Sorry :)

**Review by muatik — COMMENTED** [review]
There are only two files in the pull requests. Is this correct?

**Comment by isik5** [comment]
Yes, There are only two files in the pull requests. Correct

**Review by fkucuk — APPROVED** [review]
Authentication is coming..

**Pull request closed without merging**
